### ISSUE TITLE
Handle `Option<>` field

### ISSUE THREAD

**Issue by yanganto** [jean-airoldie/humantime-serde#13]
Hi there,

Thanks for providing this crate.

An `Option` field will be required after `humantime_serde` is put in.  The default behavior of toml can allow a missing field with an `Option` wrapper.

Following is a short example of this problem.

```rust
use serde::{Deserialize};
use std::time::Duration;

#[derive(Deserialize)]
struct Config {
    #[serde(with = "humantime_serde")]
    time: Option<Duration>,
}

fn main() {
    let _empty_config: Config = toml::from_str("").unwrap();
}
```

Console output:

```log
called `Result::unwrap()` on an `Err` value: Error { inner: Error { inner: TomlError { message: "missing field `time`", raw: Some(""), keys: [], span: Some(0..0) } } }
```

**Comment by jean-airoldie** [comment]
This issue seems to be caused by the fact that `Option<T>`'s behavior changes when you overload the deserialization via `serde(with = ...)` or `serde(deserialize_with = ...)`, [as mentioned in this issue](https://github.com/serde-rs/serde/issues/2214#issuecomment-1627645095)

To work around this problem you can do:

```rust
use serde::{Deserialize};
use std::time::Duration;

#[derive(Deserialize)]
struct Config {
    #[serde(with = "humantime_serde", default)]
    time: Option<Duration>,
}

fn main() {
    let _empty_config: Config = toml::from_str("").unwrap();
}
```

**Comment by yanganto** [comment]
Nice, thanks for the information.  :pray:
